from __future__ import annotations

TABLES: list[dict] = [
    {
        "name": "players",
        "primary_key": ["player_id"],
        "indices": [],
        "columns": [
            {"name": "player_id", "type": "BIGINT", "nullable": False, "fk": None},
            {"name": "full_name", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "first_name", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "last_name", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "birth_date", "type": "DATE", "nullable": True, "fk": None},
            {"name": "height_inches", "type": "INT", "nullable": True, "fk": None},
            {"name": "weight_lbs", "type": "INT", "nullable": True, "fk": None},
            {"name": "position", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "handedness", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "espn_slug", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
            {"name": "updated_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "teams",
        "primary_key": ["team_id"],
        "indices": [],
        "columns": [
            {"name": "team_id", "type": "INT", "nullable": False, "fk": None},
            {"name": "abbreviation", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "full_name", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "conference", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "division", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
            {"name": "updated_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "games",
        "primary_key": ["game_id"],
        "indices": [
            "games (season, game_date)",
            "games (home_team_id, season)",
            "games (away_team_id, season)",
        ],
        "columns": [
            {"name": "game_id", "type": "BIGINT", "nullable": False, "fk": None},
            {"name": "season", "type": "INT", "nullable": False, "fk": None},
            {"name": "season_type", "type": "season_type", "nullable": False, "fk": None},
            {"name": "game_date", "type": "DATE", "nullable": False, "fk": None},
            {"name": "tipoff_at", "type": "TIMESTAMPTZ", "nullable": True, "fk": None},
            {"name": "home_team_id", "type": "INT", "nullable": False, "fk": "teams.team_id"},
            {"name": "away_team_id", "type": "INT", "nullable": False, "fk": "teams.team_id"},
            {"name": "home_score", "type": "INT", "nullable": True, "fk": None},
            {"name": "away_score", "type": "INT", "nullable": True, "fk": None},
            {"name": "venue", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "attendance", "type": "INT", "nullable": True, "fk": None},
            {"name": "status", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
            {"name": "updated_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "coaches",
        "primary_key": ["coach_id"],
        "indices": [],
        "columns": [
            {"name": "coach_id", "type": "BIGINT", "nullable": False, "fk": None},
            {"name": "full_name", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "first_name", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "last_name", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "birth_date", "type": "DATE", "nullable": True, "fk": None},
            {"name": "espn_slug", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
            {"name": "updated_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "coach_games",
        "primary_key": ["game_id", "team_id", "role"],
        "indices": ["coach_games (coach_id, team_id)"],
        "columns": [
            {"name": "coach_id", "type": "BIGINT", "nullable": False, "fk": "coaches.coach_id"},
            {"name": "game_id", "type": "BIGINT", "nullable": False, "fk": "games.game_id"},
            {"name": "team_id", "type": "INT", "nullable": False, "fk": "teams.team_id"},
            {"name": "role", "type": "TEXT", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "rosters",
        "primary_key": ["season", "team_id", "player_id", "start_date"],
        "indices": ["rosters (player_id, season)"],
        "columns": [
            {"name": "season", "type": "INT", "nullable": False, "fk": None},
            {"name": "team_id", "type": "INT", "nullable": False, "fk": "teams.team_id"},
            {"name": "player_id", "type": "BIGINT", "nullable": False, "fk": "players.player_id"},
            {"name": "jersey", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "start_date", "type": "DATE", "nullable": False, "fk": None},
            {"name": "end_date", "type": "DATE", "nullable": True, "fk": None},
            {"name": "acquired_via", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "pbp_events",
        "primary_key": ["game_id", "sequence_no"],
        "indices": ["pbp_events (game_id, quarter, clock_seconds)"],
        "columns": [
            {"name": "game_id", "type": "BIGINT", "nullable": False, "fk": "games.game_id"},
            {"name": "sequence_no", "type": "INT", "nullable": False, "fk": None},
            {"name": "quarter", "type": "INT", "nullable": False, "fk": None},
            {"name": "clock_seconds", "type": "INT", "nullable": False, "fk": None},
            {"name": "wall_clock_at", "type": "TIMESTAMPTZ", "nullable": True, "fk": None},
            {"name": "team_id", "type": "INT", "nullable": True, "fk": "teams.team_id"},
            {"name": "player_id", "type": "BIGINT", "nullable": True, "fk": "players.player_id"},
            {"name": "assist_player_id", "type": "BIGINT", "nullable": True, "fk": "players.player_id"},
            {"name": "event_type", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "points_scored", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "home_score", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "away_score", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "description", "type": "TEXT", "nullable": True, "fk": None},
            {"name": "players_on_floor", "type": "JSONB", "nullable": False, "fk": None},
            {"name": "raw", "type": "JSONB", "nullable": True, "fk": None},
        ],
    },
    {
        "name": "lineup_stints",
        "primary_key": ["stint_id"],
        "indices": [
            "lineup_stints (game_id, quarter, start_clock_seconds)",
            "lineup_stints (home_lineup_hash, season)",
            "lineup_stints (away_lineup_hash, season)",
            "lineup_stints (season)",
        ],
        "columns": [
            {"name": "stint_id", "type": "BIGSERIAL", "nullable": False, "fk": None},
            {"name": "game_id", "type": "BIGINT", "nullable": False, "fk": "games.game_id"},
            {"name": "season", "type": "INT", "nullable": False, "fk": None},
            {"name": "quarter", "type": "INT", "nullable": False, "fk": None},
            {"name": "start_clock_seconds", "type": "INT", "nullable": False, "fk": None},
            {"name": "end_clock_seconds", "type": "INT", "nullable": False, "fk": None},
            {"name": "duration_seconds", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "home_team_id", "type": "INT", "nullable": False, "fk": "teams.team_id"},
            {"name": "away_team_id", "type": "INT", "nullable": False, "fk": "teams.team_id"},
            {"name": "home_lineup", "type": "INTEGER[]", "nullable": False, "fk": None},
            {"name": "away_lineup", "type": "INTEGER[]", "nullable": False, "fk": None},
            {"name": "home_lineup_hash", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "away_lineup_hash", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "home_pts", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "away_pts", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "pts", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "possessions", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "possessions_home", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "possessions_away", "type": "SMALLINT", "nullable": False, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "facts",
        "primary_key": ["fact_id"],
        "indices": ["facts (subject_type, subject_id, fact_key)"],
        "columns": [
            {"name": "fact_id", "type": "BIGSERIAL", "nullable": False, "fk": None},
            {"name": "subject_type", "type": "subject_type", "nullable": False, "fk": None},
            {"name": "subject_id", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "fact_key", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "fact_value", "type": "JSONB", "nullable": False, "fk": None},
            {"name": "source", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "season", "type": "INT", "nullable": True, "fk": None},
            {"name": "valid_from", "type": "DATE", "nullable": True, "fk": None},
            {"name": "valid_to", "type": "DATE", "nullable": True, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
            {"name": "updated_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
    {
        "name": "sim_cache",
        "primary_key": ["cache_id"],
        "indices": ["sim_cache (lineup1_hash, lineup2_hash, context_hash) UNIQUE"],
        "columns": [
            {"name": "cache_id", "type": "BIGSERIAL", "nullable": False, "fk": None},
            {"name": "lineup1_hash", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "lineup2_hash", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "context_hash", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "model_versions", "type": "JSONB", "nullable": False, "fk": None},
            {"name": "result", "type": "JSONB", "nullable": False, "fk": None},
            {"name": "hit_count", "type": "BIGINT", "nullable": False, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
            {"name": "last_hit_at", "type": "TIMESTAMPTZ", "nullable": True, "fk": None},
        ],
    },
    {
        "name": "embeddings_player",
        "primary_key": ["player_id", "season", "model_version"],
        "indices": [
            "embeddings_player USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)",
            "embeddings_player (model_version)",
        ],
        "columns": [
            {"name": "player_id", "type": "BIGINT", "nullable": False, "fk": "players.player_id"},
            {"name": "season", "type": "INT", "nullable": False, "fk": None},
            {"name": "model_version", "type": "TEXT", "nullable": False, "fk": None},
            {"name": "embedding", "type": "vector(128)", "nullable": False, "fk": None},
            {"name": "minutes_sample", "type": "INT", "nullable": True, "fk": None},
            {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "fk": None},
        ],
    },
]
